(function(P,S){function v(a,b){function c(){}c.prototype=a;var d=new c,e;for(e in b)d[e]=b[e];b.toString!==Object.prototype.toString&&(d.toString=b.toString);return d}function h(a,b){if(null==b)return null;null==b.__id__&&(b.__id__=T++);var c;null==a.hx__closures__?a.hx__closures__={}:c=a.hx__closures__[b.__id__];null==c&&(c=function(){return c.method.apply(c.scope,arguments)},c.scope=a,c.method=b,a.hx__closures__[b.__id__]=c);return c}var m=function(){return k.__string_rec(this,"")},w=function(a,
b){b=b.split("u").join("");this.r=new RegExp(a,b)};w.__name__=["EReg"];w.prototype={match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m},split:function(a){return a.replace(this.r,"#__delim__#").split("#__delim__#")},__class__:w};var r=function(){};r.__name__=["HxOverrides"];r.cca=function(a,b){var c=a.charCodeAt(b);return c!=c?void 0:c};r.substr=function(a,b,c){if(null!=b&&0!=b&&null!=c&&0>c)return"";null==c&&(c=a.length);0>b?(b=a.length+
b,0>b&&(b=0)):0>c&&(c=a.length+c-b);return a.substr(b,c)};Math.__name__=["Math"];var q=function(){};q.__name__=["Std"];q.string=function(a){return k.__string_rec(a,"")};q["int"]=function(a){return a|0};q.parseInt=function(a){var b=parseInt(a,10);0!=b||120!=r.cca(a,1)&&88!=r.cca(a,1)||(b=parseInt(a));return isNaN(b)?null:b};var y=function(){};y.__name__=["StringTools"];y.startsWith=function(a,b){return a.length>=b.length&&r.substr(a,0,b.length)==b};y.endsWith=function(a,b){var c=b.length,d=a.length;
return d>=c&&r.substr(a,d-c,c)==b};var Q=function(){};Q.__name__=["Type"];Q.getClassName=function(a){a=a.__name__;return null==a?null:a.join(".")};var f=function(){};f.__name__=["fubar","App"];f.init=function(a){if(null==a||"3.0.0"!=a.version)a={version:"3.0.0",rating:null,limit:500,autoplay:7,maxGifSize:1048576*(f.isMobile?2:3)},t.storage.setItem("fubar_config",JSON.stringify(f.config));f.config=a;f.isMobile=z.isMobile();f.service=new G("dc6zaTOxFJmzC");a=window.document.createElement("div");a.id=
"fubar";window.document.body.appendChild(a);(new A).boot(a);window.addEventListener("beforeunload",f.handleBeforeUnload,!1);window.addEventListener("contextmenu",f.handleContextMenu,!1);f.animationFrameId=window.requestAnimationFrame(f.update)};f.update=function(a){f.animationFrameId=window.requestAnimationFrame(f.update);g.current.update(window.performance.now())};f.handleContextMenu=function(a){a.preventDefault()};f.handleBeforeUnload=function(a){f.cancelAnimationFrame();t.storage.setItem("fubar_config",
JSON.stringify(f.config))};f.cancelAnimationFrame=function(){null!=f.animationFrameId&&(window.cancelAnimationFrame(f.animationFrameId),f.animationFrameId=null)};f.main=function(){window.onload=function(){window.document.body.innerHTML="";t.get("config",f.init)}};var G=function(a){this.apiKey=a};G.__name__=["fubar","Service"];G.prototype={get:function(a,b){this.request("/"+a+"?",function(a,d){null!=a?b(a,null):b(null,d.data)})},search:function(a,b,c,d,e){a="/search?q="+a.join("+");null!=b&&(a+="&limit="+
b);null!=c&&(a+="&offset="+c);null!=d&&(a+="&rating="+d);this.request(a,function(a,b){null!=a?e(a,null):e(null,b.data)})},trending:function(a,b,c){var d="/trending?";null!=a&&(d+="&limit="+a);null!=b&&(d+="&rating="+b);this.request(d,function(a,b){null!=a?c(a,null):c(null,b.data)})},request:function(a,b){var c=new XMLHttpRequest;c.open("GET","http://api.giphy.com/v1/gifs"+a+"&api_key="+this.apiKey,!0);c.onerror=function(a){b(a,null)};c.onload=function(a){b(null,JSON.parse(c.responseText))};try{c.send()}catch(d){n.trace(d,
{fileName:"Service.hx",lineNumber:65,className:"fubar.Service",methodName:"request"}),b(d,null)}},__class__:G};var R=function(){};R.__name__=["js","Browser"];R.getLocalStorage=function(){try{var a=window.localStorage;a.getItem("");return a}catch(b){return null}};var t=function(){};t.__name__=["fubar","Storage"];t.get=function(a,b){var c=t.storage.getItem("fubar_"+a);b(null==c?null:JSON.parse(c))};var g=function(a){if(null==a){a=Q.getClassName(k.getClass(this));var b=a.lastIndexOf(".");-1!=b&&(a=a.substring(b+
1));y.endsWith(a,"Activity")&&(a=a.substring(0,a.length-8));a=a.toLowerCase()}this.id=a;this.element=U._new();this.element.classList.add("activity");this.element.id=a;this.state=e.init};g.__name__=["om","app","Activity"];g.prototype={update:function(a){},replace:function(a){a.container=this.container;a.onCreate();a.onStart();this.onPause();a.onResume();this.onStop();this.onDestroy();g.stack.pop();g.stack.push(a);window.history.replaceState(null,null,null)},onCreate:function(){this.handleStateChange(e.create)},
onRestart:function(){this.handleStateChange(e.restart);this.onStart()},onStart:function(){this.handleStateChange(e.start);window.addEventListener("popstate",h(this,this.handlePopState),!1);this.container.appendChild(this.element)},onResume:function(){g.current=this;this.handleStateChange(e.resume)},onPause:function(){g.current=null;this.handleStateChange(e.pause)},onStop:function(){this.handleStateChange(e.stop);window.removeEventListener("popstate",h(this,this.handlePopState));this.element.remove()},
onDestroy:function(){this.handleStateChange(e.destroy)},handleStateChange:function(a){this.element.classList.remove(q.string(this.state));this.state=a;this.element.classList.add(q.string(a))},handlePopState:function(a){a.preventDefault();a.stopPropagation();2>g.stack.length?n.trace("no previous activity",{fileName:"Activity.hx",lineNumber:261,className:"om.app.Activity",methodName:"handlePopState"}):(g.stack.pop(),a=g.stack[g.stack.length-1],a.onRestart(),this.onPause(),a.onResume(),this.onStop(),
this.onDestroy(),window.history.replaceState(null,null,null))},boot:function(a){this.container=null!=a?a:window.document.body;g.stack.push(this);this.onCreate();this.onStart();this.onResume();return this},__class__:g};var A=function(a){g.call(this,a)};A.__name__=["fubar","app","IntroActivity"];A.__super__=g;A.prototype=v(g.prototype,{onCreate:function(){var a=this;g.prototype.onCreate.call(this);var b;b=window.document.createElement("img");b.src="image/giphy-badge-640.gif";V.once(b,"animationend",
function(b){a.replace(new B("trending"))});this.element.appendChild(b)},__class__:A});var B=function(a){g.call(this);this.mode=a};B.__name__=["fubar","app","PlayActivity"];B.__super__=g;B.prototype=v(g.prototype,{onCreate:function(){g.prototype.onCreate.call(this);this.player=new H;this.element.appendChild(this.player.element);this.controls=new I(!1);this.element.appendChild(this.controls.element);this.statusbar=window.document.createElement("div");this.statusbar.classList.add("statusbar");this.element.appendChild(this.statusbar)},
onStart:function(){var a=this;g.prototype.onStart.call(this);this.timeLastImageChange=0;this.timeLastUpdate=window.performance.now();this.timeImageShown=0;this.timePauseStart=window.performance.now();this.player.onView=function(b){a.timeLastImageChange=window.performance.now();a.controls.share.set_item(b)};this.controls.mode.onChange=function(b){switch(b[1]){case 0:switch(b[2]){case "trending":a.loadTrendingItems();break;case "search":b=a.controls.mode.searchInput.value,n.trace(b,{fileName:"PlayActivity.hx",
lineNumber:75,className:"fubar.app.PlayActivity",methodName:"onStart"}),0==b.length?n.trace("no search input",{fileName:"PlayActivity.hx",lineNumber:77,className:"fubar.app.PlayActivity",methodName:"onStart",customParams:["debug"]}):(b=(new w("(\\\\s+)","")).split(b),a.loadItems(b))}break;case 1:b=b[2],n.trace(b,{fileName:"PlayActivity.hx",lineNumber:84,className:"fubar.app.PlayActivity",methodName:"onStart"}),b=(new w("(\\\\s+)","")).split(b),a.loadItems(b)}};this.controls.play.onChange=function(b){b?
0<a.timePauseStart&&(a.timeImageShown-=window.performance.now()-a.timePauseStart,a.timePauseStart=0):a.timePauseStart=window.performance.now()};switch(this.mode){case "trending":this.loadTrendingItems();break;case "search":break;default:this.loadItem(this.mode)}this.touchInput=new J(this.player.container);this.touchInput.onGesture=h(this,this.handleTouchGesture);this.player.element.addEventListener("dblclick",h(this,this.handleDoubleClickPlayer),!1);window.document.addEventListener("visibilitychange",
h(this,this.handleVisibilityChange),!1);window.addEventListener("orientationchange",h(this,this.handleDeviceOrientationChange),!0);window.addEventListener("keydown",h(this,this.handleKeyDown),!1)},onStop:function(){g.prototype.onStop.call(this);this.touchInput.dispose();this.player.element.removeEventListener("dblclick",h(this,this.handleDoubleClickPlayer));window.removeEventListener("keydown",h(this,this.handleKeyDown));window.document.removeEventListener("visibilitychange",h(this,this.handleVisibilityChange))},
update:function(a){window.document.hidden||(this.timeImageShown+=a-this.timeLastUpdate,this.controls.play.autoplay&&(this.timeImageShown/1E3>=f.config.autoplay?(this.timeImageShown=0,this.statusbar.style.width="0px",this.player.next()):this.statusbar.style.width=q["int"](this.timeImageShown/f.config.autoplay/10*window.innerWidth/100)+"px"));this.timeLastUpdate=a},loadItem:function(a){var b=this;n.trace("Giphy.item: "+a+" ...",{fileName:"PlayActivity.hx",lineNumber:188,className:"fubar.app.PlayActivity",
methodName:"loadItem"});f.service.get(a,function(a,d){b.handleItemsLoad(a,[d])})},loadItems:function(a,b){null==b&&(b=0);n.trace("Giphy.search: "+q.string(a)+" ...",{fileName:"PlayActivity.hx",lineNumber:193,className:"fubar.app.PlayActivity",methodName:"loadItems"});f.service.search(a,f.config.limit,b,f.config.rating,h(this,this.handleItemsLoad))},loadTrendingItems:function(){n.trace("Giphy.trending ...",{fileName:"PlayActivity.hx",lineNumber:198,className:"fubar.app.PlayActivity",methodName:"loadTrendingItems"});
f.service.trending(f.config.limit,f.config.rating,h(this,this.handleItemsLoad))},handleItemsLoad:function(a,b){if(null==a){for(var c=b.length,d=0,e=0;e<b.length;){var g=b[e];++e;q.parseInt(g.images.original.size)>f.config.maxGifSize&&b.splice(d,1);d++}c-=b.length;0<c&&n.trace(c+" items filtered",{fileName:"PlayActivity.hx",lineNumber:216,className:"fubar.app.PlayActivity",methodName:"handleItemsLoad"});this.player.load(b)}},handleTouchGesture:function(a){switch(a[1]){case 0:this.controls.toggle();
break;case 3:this.controls.show();break;case 4:this.controls.hide();break;case 2:this.player.next();break;case 1:this.player.prev()}},handleDoubleClickPlayer:function(a){null!=window.document.webkitFullscreenElement?window.document.webkitExitFullscreen():window.document.documentElement.webkitRequestFullscreen()},handleKeyDown:function(a){switch(a.keyCode){case 39:this.player.next();break;case 37:this.player.prev()}},handleDeviceOrientationChange:function(a){n.trace(a,{fileName:"PlayActivity.hx",lineNumber:267,
className:"fubar.app.PlayActivity",methodName:"handleDeviceOrientationChange"})},handleVisibilityChange:function(a){window.document.hidden?this.controls.play.autoplay&&(this.timeInvisibleStart=window.performance.now()):0<this.timeInvisibleStart&&(this.timeImageShown-=window.performance.now()-this.timeInvisibleStart,this.timeInvisibleStart=0)},__class__:B});var H=function(a){null==a&&(a="#000");this.element=window.document.createElement("div");this.element.classList.add("player");this.backgroundColor=
this.element.style.backgroundColor=a;this.index=0;this.background=window.document.createElement("div");this.background.classList.add("background");this.element.appendChild(this.background);this.container=window.document.createElement("div");this.container.classList.add("media");this.element.appendChild(this.container);this.preloader=new K};H.__name__=["fubar","gui","Player"];H.prototype={onView:function(a){},load:function(a,b,c){null==b&&(b=0);null!=this.items&&this.clear();this.items=a;this.pagination=
c;this["goto"](b)},"goto":function(a){var b=this;if(!(a>this.items.length||0>a)){var c=this.index+1==a,d=this.index-1==a;this.index=a;n.trace("goto "+this.index,{fileName:"Player.hx",lineNumber:82,className:"fubar.gui.Player",methodName:"goto"});var e=this.items[this.index];null!=this.nextView&&this.nextView.remove(!0);this.nextView=new L(e);this.nextView.onLoad=function(){b.nextView=null;b.onView(e);c&&b.index<b.items.length-1&&b.preload(b.items[b.index+1]);d&&0<b.index&&b.preload(b.items[b.index-
1])};this.container.appendChild(this.nextView.element);null!=this.currentView&&this.currentView.remove();this.currentView=this.nextView}},prev:function(){if(0<this.index)this["goto"](this.index-1)},next:function(){if(this.index<this.items.length-1)this["goto"](this.index+1)},clear:function(){for(;null!=this.container.firstChild;)this.container.removeChild(this.container.firstChild);this.items=[];this.index=0;this.preloader.dispose()},preload:function(a,b){this.preloader.preload(a.images.original.url,
b)},__class__:H};var l={__ename__:!0,__constructs__:["tap","right","left","up","down"],tap:["tap",0]};l.tap.toString=m;l.tap.__enum__=l;l.right=function(a){a=["right",1,a];a.__enum__=l;a.toString=m;return a};l.left=function(a){a=["left",2,a];a.__enum__=l;a.toString=m;return a};l.up=function(a){a=["up",3,a];a.__enum__=l;a.toString=m;return a};l.down=function(a){a=["down",4,a];a.__enum__=l;a.toString=m;return a};var J=function(a,b){null==b&&(b=50);this.threshold=b;this.start={x:-1,y:-1};this.move={x:-1,
y:-1};a.addEventListener("touchstart",h(this,this.handleTouchStart),!1);a.addEventListener("touchmove",h(this,this.handleTouchMove),!1);a.addEventListener("touchend",h(this,this.handleTouchEnd),!1);this.enabled=!0};J.__name__=["fubar","gui","TouchInput"];J.prototype={onStart:function(a){},onMove:function(a){},onEnd:function(a){},onGesture:function(a){},dispose:function(){this.enabled=!1;this.element.removeEventListener("touchstart",h(this,this.handleTouchStart));this.element.removeEventListener("touchmove",
h(this,this.handleTouchMove));this.element.removeEventListener("touchend",h(this,this.handleTouchEnd))},handleTouchStart:function(a){if(this.enabled&&null!=a.touches){var b=a.touches[0];this.start.x=b.pageX;this.start.y=b.pageY;this.onStart(a)}},handleTouchMove:function(a){if(this.enabled&&(a.preventDefault(),a.stopPropagation(),null!=a.touches)){var b=a.touches[0];this.move.x=b.pageX;this.move.y=b.pageY;this.onMove(a)}},handleTouchEnd:function(a){if(this.enabled){a.preventDefault();a.stopPropagation();
this.onEnd(a);if(-1<this.start.x&&-1<this.move.x){a=this.start.x>this.move.x?this.start.x-this.move.x:this.move.x-this.start.x;var b;b=this.start.y>this.move.y?this.start.y-this.move.y:this.move.y-this.start.y;if(a>this.threshold)this.onGesture(this.start.x<this.move.x?l.right(a):l.left(a));else if(b>this.threshold)this.onGesture(this.start.y<this.move.y?l.down(b):l.up(b))}else this.onGesture(l.tap);this.start.x=this.start.y=this.move.x=this.move.y=-1}},__class__:J};var p=function(a){this.hidden=
!1;this.element=window.document.createElement("div");this.element.classList.add("menu",a,"shown")};p.__name__=["fubar","gui","player","ControlMenu"];p.prototype={show:function(){this.hidden=!1;this.element.classList.add("shown");this.element.classList.remove("hidden")},hide:function(){this.hidden=!0;this.element.classList.remove("shown");this.element.classList.add("hidden")},addIconButton:function(a){a=this.createIconButton(a);this.element.appendChild(a);return a},createIconButton:function(a){var b;
b=window.document.createElement("img");b.classList.add("button",a);b.src="image/ic_"+a+".png";return b},__class__:p};var C=function(a){p.call(this,"autoplay");this.buttonPlay=this.addIconButton("play");this.buttonPause=this.addIconButton("pause");this.set(a);this.element.addEventListener("click",h(this,this.handleClick),!1)};C.__name__=["fubar","gui","player","ControlMenuAutoplay"];C.__super__=p;C.prototype=v(p.prototype,{onChange:function(a){},handleClick:function(a){a.stopPropagation();a.preventDefault();
this.set(!this.autoplay)},set:function(a){(this.autoplay=a)?(this.buttonPlay.style.display="none",this.buttonPause.style.display="inline-block"):(this.buttonPlay.style.display="inline-block",this.buttonPause.style.display="none");this.onChange(a)},__class__:C});var D={__ename__:!0,__constructs__:["mode","search"],mode:function(a){a=["mode",0,a];a.__enum__=D;a.toString=m;return a},search:function(a){a=["search",1,a];a.__enum__=D;a.toString=m;return a}},E=function(){var a=this;p.call(this,"mode");this.trendingButton=
this.addIconButton("trending");this.trendingButton.onclick=function(b){a.setMode("search");a.onChange(D.mode("search"))};this.searchButton=this.addIconButton("search");this.searchButton.style.display="none";this.searchButton.onclick=function(b){a.setMode("trending");a.onChange(D.mode("trending"))};this.searchInput=window.document.createElement("input");this.searchInput.type="search";this.searchInput.addEventListener("input",h(this,this.handleSearchInput),!1);this.searchInput.addEventListener("search",
h(this,this.handleSearchEnter),!1);this.element.appendChild(this.searchInput);this.searchClear=this.addIconButton("clear");this.searchClear.addEventListener("click",h(this,this.handleClearClick),!1)};E.__name__=["fubar","gui","player","ControlMenuMode"];E.__super__=p;E.prototype=v(p.prototype,{onChange:function(a){},setMode:function(a){switch(a){case "trending":this.trendingButton.style.display="inline-block";this.searchButton.style.display="none";this.searchInput.style.display="none";this.searchClear.style.display=
"none";break;case "search":this.trendingButton.style.display="none",this.searchButton.style.display="inline-block",this.searchInput.style.display="inline-block",0==this.searchInput.value.length?(this.searchClear.style.display="none",this.searchInput.focus()):this.searchClear.style.display="inline-block"}},setSearchText:function(a){this.searchInput.value=a;this.updateSearchInput()},updateSearchInput:function(){this.searchInput.style.width=(16.8+14*this.searchInput.value.length|0)+"px";0==this.searchInput.value.length?
(this.searchClear.style.display="none",this.searchInput.focus()):this.searchClear.style.display="inline-block"},handleSearchInput:function(a){this.updateSearchInput()},handleSearchEnter:function(a){a.preventDefault();a.stopPropagation();this.searchInput.blur();this.onChange(D.search(this.searchInput.value))},handleClearClick:function(a){a.stopPropagation();a.preventDefault();this.setSearchText("");this.searchInput.focus()},__class__:E});var F=function(){var a=this;p.call(this,"share");this.isMenuOpen=
!1;this.menu=window.document.createElement("div");this.menu.classList.add("menu");this.element.appendChild(this.menu);this.optShare=this.addMenuOption("share",function(){null!=a.item&&window.open(a.item.bitly_url,"_blank")});this.optLink=this.addMenuOption("link",function(){});this.optLink.target="_blank";this.optDownload=this.addMenuOption("download");this.more=this.createIconButton("more_vert");this.more.onclick=h(this,this.toggleMenu);this.element.appendChild(this.more)};F.__name__=["fubar","gui",
"player","ControlMenuShare"];F.__super__=p;F.prototype=v(p.prototype,{set_item:function(a){this.item=a;null==this.item?(this.optLink.href=null,this.optDownload.href=null,this.optDownload.download=null,this.optShare.style.display="none",this.optLink.style.display="none",this.optDownload.style.display="none"):(a=this.item.source_post_url,null==a||0==a.length?(this.optLink.href=null,this.optLink.style.display="none"):(this.optLink.href=a,this.optLink.style.display="inline-block",a=-1!=a.indexOf("reddit.com")?
"reddit":-1!=a.indexOf("tumblr.com")?"tumblr":-1!=a.indexOf("youtube.com")?"youtube":"link",this.optLink.children[0].src="image/ic_"+a+".png"),this.optDownload.href=this.item.images.original.url,this.optDownload.download="giphy-"+this.item.id+".gif");return this.item},openMenu:function(){this.isMenuOpen=!0;this.menu.style.display="inline-block";return!0},closeMenu:function(){this.isMenuOpen=!1;this.menu.style.display="none";return!1},toggleMenu:function(){return this.isMenuOpen?this.closeMenu():this.openMenu()},
addMenuOption:function(a,b){var c;c=window.document.createElement("a");c.classList.add("option");var d;d=window.document.createElement("img");d.src="image/ic_"+a+".png";d.classList.add("button");c.appendChild(d);this.menu.appendChild(c);null!=b&&(c.onclick=b,c.ontouchstart=b);return c},__class__:F});var I=function(a){this.hidden=!1;this.menus=[];this.element=window.document.createElement("div");this.element.classList.add("controls","shown");this.play=this.addControlMenu(new C(a));this.mode=this.addControlMenu(new E);
this.share=this.addControlMenu(new F)};I.__name__=["fubar","gui","player","Controls"];I.prototype={show:function(){this.hidden=!1;this.element.classList.add("shown");this.element.classList.remove("hidden");for(var a=0,b=this.menus;a<b.length;){var c=b[a];++a;c.show()}},hide:function(){this.hidden=!0;this.element.classList.remove("shown");this.element.classList.add("hidden");for(var a=0,b=this.menus;a<b.length;){var c=b[a];++a;c.hide()}},toggle:function(){this.hidden?this.show():this.hide()},addControlMenu:function(a){this.element.appendChild(a.element);
this.menus.push(a);return a},__class__:I};var L=function(a){var b=this;this.element=window.document.createElement("div");this.element.classList.add("item","inc");this.element.addEventListener("animationend",function(a){switch(a.animationName){case "item_inc":b.element.classList.remove("inc");break;case "item_out":b.element.remove();break;default:y.startsWith(a.animationName,"item_")&&b.element.classList.remove(r.substr(a.animationName,5,null))}},!1);this.gif=window.document.createElement("img");this.gif.classList.add("gif");
this.gif.onload=function(){b.still.style.display="none";b.gif.style.display="inline-block";b.gif.classList.add("playing");b.element.appendChild(b.gif);b.onLoad()};this.still=window.document.createElement("img");this.still.onload=function(){b.still.style.display="inline-block"};this.still.src=a.images.original_still.url;this.element.appendChild(this.still);this.loader=new M;this.loader.onProgress=function(a,b){};this.loader.onComplete=function(a){b.gif.src=a};this.loader.load(a.images.original.url)};
L.__name__=["fubar","gui","player","ItemView"];L.prototype={onLoad:function(){},remove:function(a){null==a&&(a=!1);this.loader.abort();this.element.classList.remove("playing");a?this.element.remove():(this.element.classList.remove("playing"),this.element.classList.add("out"))},__class__:L};var M=function(){};M.__name__=["fubar","net","ImageLoader"];M.prototype={onProgress:function(a,b){},onComplete:function(a){},onError:function(a){},load:function(a){var b=this;this.xhr=new XMLHttpRequest;this.xhr.responseType=
"blob";this.xhr.open("GET",a,!0);this.xhr.onload=function(a){b.onComplete(window.URL.createObjectURL(b.xhr.response));b.xhr=null};this.xhr.onprogress=function(a){b.onProgress(a.total,a.loaded)};this.xhr.onerror=function(a){b.onError(a);b.xhr=null};this.xhr.send()},abort:function(){null!=this.xhr&&(n.trace("aborting image load",{fileName:"ImageLoader.hx",lineNumber:37,className:"fubar.net.ImageLoader",methodName:"abort"}),this.xhr.abort())},__class__:M};var K=function(a){null==a&&(a=4);this.maxPreloads=
a;this.map=new x;this.numPreloads=0};K.__name__=["fubar","net","ImagePreloader"];K.prototype={preload:function(a,b){var c=this;if(!this.map.exists(a))if(this.numPreloads==this.maxPreloads)n.trace("max preload size reached",{fileName:"ImagePreloader.hx",lineNumber:26,className:"fubar.net.ImagePreloader",methodName:"preload"});else{var d=new XMLHttpRequest;this.map.set(a,d);this.numPreloads++;d.responseType="blob";d.open("GET",a,!0);d.onload=function(d){c.map.remove(a);c.numPreloads--;null!=b&&b(null)};
d.onerror=function(d){c.map.remove(a);c.numPreloads--;null!=b&&b(d)};d.send()}},dispose:function(){for(var a=this.map.iterator();a.hasNext();)a.next().abort();this.map=new x},__class__:K};var u=function(){};u.__name__=["haxe","IMap"];var n=function(){};n.__name__=["haxe","Log"];n.trace=function(a,b){k.__trace(a,b)};var N=function(a,b){this.map=a;this.keys=b;this.index=0;this.count=b.length};N.__name__=["haxe","ds","_StringMap","StringMapIterator"];N.prototype={hasNext:function(){return this.index<
this.count},next:function(){return this.map.get(this.keys[this.index++])},__class__:N};var x=function(){this.h={}};x.__name__=["haxe","ds","StringMap"];x.__interfaces__=[u];x.prototype={set:function(a,b){null!=O[a]?this.setReserved(a,b):this.h[a]=b},get:function(a){return null!=O[a]?this.getReserved(a):this.h[a]},exists:function(a){return null!=O[a]?this.existsReserved(a):this.h.hasOwnProperty(a)},setReserved:function(a,b){null==this.rh&&(this.rh={});this.rh["$"+a]=b},getReserved:function(a){return null==
this.rh?null:this.rh["$"+a]},existsReserved:function(a){return null==this.rh?!1:this.rh.hasOwnProperty("$"+a)},remove:function(a){if(null!=O[a]){a="$"+a;if(null==this.rh||!this.rh.hasOwnProperty(a))return!1;delete this.rh[a]}else{if(!this.h.hasOwnProperty(a))return!1;delete this.h[a]}return!0},arrayKeys:function(){var a=[],b;for(b in this.h)this.h.hasOwnProperty(b)&&a.push(b);if(null!=this.rh)for(b in this.rh)36==b.charCodeAt(0)&&a.push(b.substr(1));return a},iterator:function(){return new N(this,
this.arrayKeys())},__class__:x};var k=function(){};k.__name__=["js","Boot"];k.__unhtml=function(a){return a.split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;")};k.__trace=function(a,b){var c;c=null!=b?b.fileName+":"+b.lineNumber+": ":"";c+=k.__string_rec(a,"");if(null!=b&&null!=b.customParams)for(var d=0,e=b.customParams;d<e.length;){var f=e[d];++d;c+=","+k.__string_rec(f,"")}var g;"undefined"!=typeof document&&null!=(g=document.getElementById("haxe:trace"))?g.innerHTML+=k.__unhtml(c)+
"<br/>":"undefined"!=typeof P&&null!=P.log&&P.log(c)};k.getClass=function(a){if(a instanceof Array&&null==a.__enum__)return Array;var b=a.__class__;if(null!=b)return b;a=k.__nativeClassName(a);return null!=a?k.__resolveNativeClass(a):null};k.__string_rec=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&(c="object");switch(c){case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];c=a[0]+"(";b+="\t";for(var d=
2,e=a.length;d<e;)var f=d++,c=2!=f?c+(","+k.__string_rec(a[f],b)):c+k.__string_rec(a[f],b);return c+")"}c=a.length;d="[";b+="\t";for(e=0;e<c;)f=e++,d+=(0<f?",":"")+k.__string_rec(a[f],b);return d+"]"}try{d=a.toString}catch(g){return"???"}if(null!=d&&d!=Object.toString&&"function"==typeof d&&(c=a.toString(),"[object Object]"!=c))return c;c=null;d="{\n";b+="\t";e=null!=a.hasOwnProperty;for(c in a)e&&!a.hasOwnProperty(c)||"prototype"==c||"__class__"==c||"__super__"==c||"__interfaces__"==c||"__properties__"==
c||(2!=d.length&&(d+=", \n"),d+=b+c+" : "+k.__string_rec(a[c],b));b=b.substring(1);return d+("\n"+b+"}");case "function":return"<function>";case "string":return a;default:return String(a)}};k.__nativeClassName=function(a){a=k.__toStr.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};k.__resolveNativeClass=function(a){return S[a]};u=function(){};u.__name__=["om","Error"];u.__super__=Error;u.prototype=v(Error.prototype,{__class__:u});var z=function(){};z.__name__=["om",
"System"];z.isMobile=function(a,b){null==a&&(a=window.navigator.userAgent);null==b&&(b=z.mobileUserAgents);return(new w(b.join("|"),"i")).match(a)};var e={__ename__:!0,__constructs__:"init create start restart resume pause stop destroy".split(" "),init:["init",0]};e.init.toString=m;e.init.__enum__=e;e.create=["create",1];e.create.toString=m;e.create.__enum__=e;e.start=["start",2];e.start.toString=m;e.start.__enum__=e;e.restart=["restart",3];e.restart.toString=m;e.restart.__enum__=e;e.resume=["resume",
4];e.resume.toString=m;e.resume.__enum__=e;e.pause=["pause",5];e.pause.toString=m;e.pause.__enum__=e;e.stop=["stop",6];e.stop.toString=m;e.stop.__enum__=e;e.destroy=["destroy",7];e.destroy.toString=m;e.destroy.__enum__=e;var U={__name__:["om","html","_DivElement","DivElement_Impl_"],_new:function(a,b){var c;c=window.document.createElement("div");null!=a&&(c.textContent=a);if(null!=b)for(var d=0;d<b.length;){var e=b[d];++d;c.classList.add(e)}return c}},V={__name__:["om","html","_ImageElement","ImageElement_Impl_"],
once:function(a,b,c,d){var e=null,e=function(d){c(d);a.removeEventListener(b,e)};a.addEventListener(b,e,d);return a}},T=0;String.prototype.__class__=String;String.__name__=["String"];Array.__name__=["Array"];var O={};t.storage=R.getLocalStorage();g.stack=[];k.__toStr={}.toString;z.mobileUserAgents="Android;webOS;iPhone;iPad;iPod;BlackBerry;IEMobile;Opera Mini".split(";");f.main()})("undefined"!=typeof console?console:{log:function(){}},"undefined"!=typeof window?window:"undefined"!=typeof global?
global:"undefined"!=typeof self?self:this);
